mongodb:
    primary:
        host: localhost
        port: 27017
        database: test
    secondary:
        host: localhost
        port: 27017
        database: local
server:
    port: 8004
    servlet:
        context-path: /mongo
    uri-encoding: utf-8